name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by Cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cypress Run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: ui-electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 316deccc-28d0-4ec0-b50c-d0eb832b9a3f
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

